// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: oauth2_server_service/v1/oauth2.proto

package oauth2_server_servicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Oauth2ServiceClient is the client API for Oauth2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Oauth2ServiceClient interface {
	PasswordGrant(ctx context.Context, in *PasswordGrantRequest, opts ...grpc.CallOption) (*PasswordGrantResponse, error)
	AuthorizationCodeGrant(ctx context.Context, in *AuthorizationCodeGrantRequest, opts ...grpc.CallOption) (*AuthorizationCodeGrantResponse, error)
	RefreshTokenGrant(ctx context.Context, in *RefreshTokenGrantRequest, opts ...grpc.CallOption) (*RefreshTokenGrantResponse, error)
	ClientCredentialsGrant(ctx context.Context, in *ClientCredentialsGrantRequest, opts ...grpc.CallOption) (*ClientCredentialsGrantResponse, error)
}

type oauth2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOauth2ServiceClient(cc grpc.ClientConnInterface) Oauth2ServiceClient {
	return &oauth2ServiceClient{cc}
}

func (c *oauth2ServiceClient) PasswordGrant(ctx context.Context, in *PasswordGrantRequest, opts ...grpc.CallOption) (*PasswordGrantResponse, error) {
	out := new(PasswordGrantResponse)
	err := c.cc.Invoke(ctx, "/oauth2_server_service.v1.Oauth2Service/PasswordGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2ServiceClient) AuthorizationCodeGrant(ctx context.Context, in *AuthorizationCodeGrantRequest, opts ...grpc.CallOption) (*AuthorizationCodeGrantResponse, error) {
	out := new(AuthorizationCodeGrantResponse)
	err := c.cc.Invoke(ctx, "/oauth2_server_service.v1.Oauth2Service/AuthorizationCodeGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2ServiceClient) RefreshTokenGrant(ctx context.Context, in *RefreshTokenGrantRequest, opts ...grpc.CallOption) (*RefreshTokenGrantResponse, error) {
	out := new(RefreshTokenGrantResponse)
	err := c.cc.Invoke(ctx, "/oauth2_server_service.v1.Oauth2Service/RefreshTokenGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2ServiceClient) ClientCredentialsGrant(ctx context.Context, in *ClientCredentialsGrantRequest, opts ...grpc.CallOption) (*ClientCredentialsGrantResponse, error) {
	out := new(ClientCredentialsGrantResponse)
	err := c.cc.Invoke(ctx, "/oauth2_server_service.v1.Oauth2Service/ClientCredentialsGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Oauth2ServiceServer is the server API for Oauth2Service service.
// All implementations should embed UnimplementedOauth2ServiceServer
// for forward compatibility
type Oauth2ServiceServer interface {
	PasswordGrant(context.Context, *PasswordGrantRequest) (*PasswordGrantResponse, error)
	AuthorizationCodeGrant(context.Context, *AuthorizationCodeGrantRequest) (*AuthorizationCodeGrantResponse, error)
	RefreshTokenGrant(context.Context, *RefreshTokenGrantRequest) (*RefreshTokenGrantResponse, error)
	ClientCredentialsGrant(context.Context, *ClientCredentialsGrantRequest) (*ClientCredentialsGrantResponse, error)
}

// UnimplementedOauth2ServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOauth2ServiceServer struct {
}

func (UnimplementedOauth2ServiceServer) PasswordGrant(context.Context, *PasswordGrantRequest) (*PasswordGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordGrant not implemented")
}
func (UnimplementedOauth2ServiceServer) AuthorizationCodeGrant(context.Context, *AuthorizationCodeGrantRequest) (*AuthorizationCodeGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizationCodeGrant not implemented")
}
func (UnimplementedOauth2ServiceServer) RefreshTokenGrant(context.Context, *RefreshTokenGrantRequest) (*RefreshTokenGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshTokenGrant not implemented")
}
func (UnimplementedOauth2ServiceServer) ClientCredentialsGrant(context.Context, *ClientCredentialsGrantRequest) (*ClientCredentialsGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientCredentialsGrant not implemented")
}

// UnsafeOauth2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Oauth2ServiceServer will
// result in compilation errors.
type UnsafeOauth2ServiceServer interface {
	mustEmbedUnimplementedOauth2ServiceServer()
}

func RegisterOauth2ServiceServer(s grpc.ServiceRegistrar, srv Oauth2ServiceServer) {
	s.RegisterService(&Oauth2Service_ServiceDesc, srv)
}

func _Oauth2Service_PasswordGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Oauth2ServiceServer).PasswordGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth2_server_service.v1.Oauth2Service/PasswordGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Oauth2ServiceServer).PasswordGrant(ctx, req.(*PasswordGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oauth2Service_AuthorizationCodeGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationCodeGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Oauth2ServiceServer).AuthorizationCodeGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth2_server_service.v1.Oauth2Service/AuthorizationCodeGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Oauth2ServiceServer).AuthorizationCodeGrant(ctx, req.(*AuthorizationCodeGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oauth2Service_RefreshTokenGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Oauth2ServiceServer).RefreshTokenGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth2_server_service.v1.Oauth2Service/RefreshTokenGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Oauth2ServiceServer).RefreshTokenGrant(ctx, req.(*RefreshTokenGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oauth2Service_ClientCredentialsGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientCredentialsGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Oauth2ServiceServer).ClientCredentialsGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth2_server_service.v1.Oauth2Service/ClientCredentialsGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Oauth2ServiceServer).ClientCredentialsGrant(ctx, req.(*ClientCredentialsGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Oauth2Service_ServiceDesc is the grpc.ServiceDesc for Oauth2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oauth2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oauth2_server_service.v1.Oauth2Service",
	HandlerType: (*Oauth2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PasswordGrant",
			Handler:    _Oauth2Service_PasswordGrant_Handler,
		},
		{
			MethodName: "AuthorizationCodeGrant",
			Handler:    _Oauth2Service_AuthorizationCodeGrant_Handler,
		},
		{
			MethodName: "RefreshTokenGrant",
			Handler:    _Oauth2Service_RefreshTokenGrant_Handler,
		},
		{
			MethodName: "ClientCredentialsGrant",
			Handler:    _Oauth2Service_ClientCredentialsGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth2_server_service/v1/oauth2.proto",
}
